### PR TITLE
Update text analytics sample

### PR DESCRIPTION
**Pull request by cxznmhdcxz**
## Purpose

* update samples\language\text_analytics_samples.py, now uses t2 text analytics sdk

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```
## Other Information

no change in other samples

### CODE REVIEW

**Comment by kaerm** [comment]
hey @cxznmhdcxz some checks here failed - could you get that fixed?

cc: @jongio

**Comment by v-xuto** [comment]
1. Update text analytics from track1 to track2; file: samples\language\text_analytics_samples.py
2. Update anomaly detector from track1 to track2;  file: samples\anomaly_detector_samples.py 

@jongio for notification.

**Comment by jongio** [comment]
@PatrickFarley - Can you review?

**Comment by aahill** [comment]
The Text Analytics sample looks good - @mrbullwinkle for Anomaly Detector

**Review by mrbullwinkle — APPROVED** [review]
Approving the Anomaly Detector changes.

**Pull request merged**
